# Logging, minimum without colors
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y

# Zephyr sensor API
CONFIG_SENSOR=y
CONFIG_SENSOR_INFO=y

# I2C driver
CONFIG_I2C=y

# BME/P driver
CONFIG_BME280=y

# run "west build -t menuconfig" and look for BME for more 
# kconfig options