# Logging, minimum without colors
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y

# Print network debug
CONFIG_NET_LOG=y

# GPIO Driver (already activated by minimum config)
CONFIG_GPIO=y

# # Wi-Fi
# # Enable the Wi-Fi relevant configurations
CONFIG_WIFI=y
# Disable Zephyr WPA since there is an external chip
# CONFIG_WIFI_NM_WPA_SUPPLICANT=n

# # Configure the Wi-Fi credentials
CONFIG_WIFI_CREDENTIALS=y
CONFIG_WIFI_CREDENTIALS_STATIC=y
CONFIG_WIFI_CREDENTIALS_STATIC_SSID="your SSID"
CONFIG_WIFI_CREDENTIALS_STATIC_PASSWORD="your password"

# Enable the Network Management relevant configurations
# CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
# CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=16
# CONFIG_NET_L2_WIFI_MGMT=y
# CONFIG_WIFI_LOG_LEVEL_DBG=y

# # Enable the Connection Manager 
# CONFIG_NET_CONNECTION_MANAGER=y
# CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=5200

# # System settings
# CONFIG_NEWLIB_LIBC=y
# CONFIG_NEWLIB_LIBC_NANO=n

# # Networking
CONFIG_NETWORKING=y
CONFIG_TEST_RANDOM_GENERATOR=y
# CONFIG_NET_SOCKETS=y
CONFIG_NET_L2_ETHERNET=y

CONFIG_NET_IPV4=y
# CONFIG_NET_IPV6=n
CONFIG_NET_DHCPV4=y

# # Memory
# CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=5200
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048

# CONFIG_NET_PKT_RX_COUNT=10
# CONFIG_NET_PKT_TX_COUNT=10
# CONFIG_NET_BUF_RX_COUNT=20
# CONFIG_NET_BUF_TX_COUNT=20
# CONFIG_NET_MAX_CONTEXTS=10

